# Generated by Django 4.0.4 on 2022-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
